# Generated by Django 3.1 on 2020-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('choice1', models.CharField(max_length=1000)),
                ('choice2', models.CharField(max_length=1000)),
                ('choice3', models.CharField(max_length=1000)),
                ('choice4', models.CharField(max_length=1000)),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
